---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copy Tmux Config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME}}/.tmux.conf"
- name: "Install tpm"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm" 
- name: "Make Tmux Logs Directory"
  file:
    path: "{{ ansible_env.HOME }}/.tmux/logs"
    state: directory 
